server:
  port: 8040


jwt:
  access:
    expiration: 86400
  refresh:
    expiration: 6048000

spring:
  datasource:
    password: root
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jazzmaniche@gmail.com
    password: mszwhgpdrpjhoykj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

